# Generated by Django 4.2.4 on 2023-08-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_color_student_color"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="color",),
        migrations.DeleteModel(name="Color",),
    ]
